// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQBF7Gs8cOqldb1dUhxdbx7NjCILNpdy8',
    appId: '1:538852288440:web:4f4861900bcd01091a514d',
    messagingSenderId: '538852288440',
    projectId: 'epfin-a8767',
    authDomain: 'epfin-a8767.firebaseapp.com',
    storageBucket: 'epfin-a8767.firebasestorage.app',
    measurementId: 'G-ZEQPWB61JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2q6chnfl9No8ThAFC3Utbmp7DU1VjMw',
    appId: '1:538852288440:android:e8f24969a34730b31a514d',
    messagingSenderId: '538852288440',
    projectId: 'epfin-a8767',
    storageBucket: 'epfin-a8767.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZ3_r_HJNowOMm1ML3qJNp9FNld3WJds',
    appId: '1:538852288440:ios:7eb18e6fa4fee17d1a514d',
    messagingSenderId: '538852288440',
    projectId: 'epfin-a8767',
    storageBucket: 'epfin-a8767.firebasestorage.app',
    iosBundleId: 'com.energypac.epfin.io',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVZ3_r_HJNowOMm1ML3qJNp9FNld3WJds',
    appId: '1:538852288440:ios:9f2fb59fda65f3d01a514d',
    messagingSenderId: '538852288440',
    projectId: 'epfin-a8767',
    storageBucket: 'epfin-a8767.firebasestorage.app',
    iosBundleId: 'com.energypac.epfin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQBF7Gs8cOqldb1dUhxdbx7NjCILNpdy8',
    appId: '1:538852288440:web:5b4c229aacfe79bf1a514d',
    messagingSenderId: '538852288440',
    projectId: 'epfin-a8767',
    authDomain: 'epfin-a8767.firebaseapp.com',
    storageBucket: 'epfin-a8767.firebasestorage.app',
    measurementId: 'G-LNV4PVL82S',
  );
}
